export const SEND_SUBSCRIPTION = "SEND_SUBSCRIPTION";
export const ADD_TO_COUNTER = "ADD_TO_COUNTER";
export const SUBTRACT_TO_COUNTER = "SUBTRACT_TO_COUNTER";
export const SAVE_MESSAGES = "SAVE_MESSAGES";
export const USER_SAID_HI = "USER_SAID_HI";
export const USER_SAID_BYE = "USER_SAID_BYE";